### ISSUE TITLE
Add Programmatic Upload Support

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther-analysis#10]
Add an `upload` command to the `panther-cli` tool that zips a specified directory, and invokes the `BulkUpload` endpoint of the `analysis-api` lambda function in [panther](https://github.com/panther-labs/panther).

This will support a complete CLI based developer workflow for new rules and policies without having to access the panther UI.

**Comment by jacknagz** [comment]
Closed via https://github.com/panther-labs/panther-analysis/pull/12
