### ISSUE TITLE
OneLogin.ActiveLoginActivity TypeError

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther-analysis#122]
One of our customer accounts [paged us](https://runpanther.pagerduty.com/incidents/P9OUGDC) with the following error message:

> failed to run rule OneLogin.ActiveLoginActivity RuleResult TypeError("'int' object is not iterable")

This error has actually been present for several weeks and triggers on nearly every record from what I can tell.

Double-check all assumptions about any iterables in the rule. For example, `if x in some_set`, make sure `some_set` is guaranteed to be an iterable, and not an integer.

**Comment by nhakmiller** [comment]
We think this was fixed in https://github.com/panther-labs/panther-analysis/pull/109, this particular customer just hasn't updated their policies/rules recently most likely. I'll reach out to them about updating.
