### ISSUE TITLE
Initial Rule Set using DataModels

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther-analysis#123]
### Description

Create DataModel for a few log sources. Create a few rules that leverages the DataModels and the `udm` method.

### Related Services

BE support for standard fields / accessing standard fields. 

### Acceptance Criteria

- Rules use standard field accesses

**Comment by mattthetraveler** [comment]
hey @lindsey-w is this something we'll have in 1.14?

**Comment by lindsey-w** [comment]
Hey @mattthetraveler - turns out we need to publish a new version of the `panther_analysis_tool` before I can push up the new data models/rules here.  I suspect that will be done early next week; so this might need the 1.15 milestone then.
