### ISSUE TITLE
Typo in regex?

### ISSUE THREAD

**Issue by zestysoft** [panther-labs/panther-analysis#1435]
https://github.com/panther-labs/panther-analysis/blame/d02d3e76d1994587a2b8fe5be3c7835bbe132520/rules/zoom_operation_rules/zoom_user_promoted_to_privileged_role.py#L9

I think the letter 'c' in this regex isn't supposed to be there:
r"[\w.+-c]+@[\w-]+\.[\w.-]+"

My understanding is that when the dash isn't at the end of the listed items in the brackets, it is interpreted as a range operator, so this rule is saying all word characters, a period and any character between the plus sign and the letter c (inclusive).

Thankfully, the dash is between the range of + and c, so this was still matching on emails that have a dash in the name part.

**Comment by arielkr256** [comment]
@zestysoft good catch!  I noticed a couple other minor issues as well.  Please check out the attached PR and let me know if you notice anything else!
