### ISSUE TITLE
Review Dedup & Title Functions for noisy Alerts

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther-analysis#167]
We have received reports that a number of rules, specifically G Suite related ones, can be very noisy out of the box. We should do a check of title & dedup functions across our detection packs in an effort to reduce alert fatigue.

We should look for:
- Any dedup function based on `p_row_id`, and refactor this
- Any dedup function based on three or more different fields in an event, and refactor these
- Any dedup function based on high cardinality fields (IP, host ID, etc.) and see if there is a better alternative field to use (user name, account ID)  that will do a better job aggregating similar alerts

**Comment by kostaspap** [comment]
> Any dedup function based on p_row_id, and refactor this

100% agree, this should be considered an anti-pattern.
