### ISSUE TITLE
How to import policies in Panther community?

### ISSUE THREAD

**Issue by guilhermerezendemarques** [panther-labs/panther-analysis#205]

**Comment by wey-chiang** [comment]
Not entirely sure what the question is asking here.

Generally speaking, policies should not be imported into other detections to be used. If there are common components that would be useful in other detections, then those should belong in a global helper.

If the question is around how do you get policies into Panther, then you can either use the [panther-analysis-tool](https://github.com/panther-labs/panther_analysis_tool), the Bulk Uploader functionality in the UI, or manually create the detection within Panther.

If you need more help on this issue, please feel free to open a new issue!
