### ISSUE TITLE
Move _rules and _policies from root to a subfolder

### ISSUE THREAD

**Issue by slw07g** [panther-labs/panther-analysis#300]
Curious what your thoughts are on migrating the many `*_rules` and `*_policies` folders from the root of the repo into sub-folders such as `original_rules` and `original_policies`. 

It's mostly a personal preference, but I think it'd make it easier on the eyes for most folks.

**Comment by sjatearnin** [comment]
Yes, and make it easier to map a rule/policy from GUI to code base. Right now, I feel like I have to hunt through the code base to find where a specific rule/logic lives.

**Comment by edyesed** [comment]
I know it's been a while, and your suggestion just moved into the primary branch ( and a new release ) @slw07g 👍
