### ISSUE TITLE
Return data structure needs to be independent of the geoip info provider

### ISSUE THREAD

**Issue by sjatearnin** [panther-labs/panther-analysis#323]
https://github.com/panther-labs/panther-analysis/blob/cb1b0af1b9f656c3567bc731230cec27153eb75f/global_helpers/panther_oss_helpers.py#L342

The current implementation simply passes/returns the data structure (json) as returned by ipinfo. The `geoinfo_from_ip` should abstract the return data structure so it is independent of the geoip lookup provider. 

For example, ipdata.co returns `country_code` and `country_name` but no `country` but ipinfo.co returns a single key `country`. Similarly, ipinfo returns `org` whereas ipdata returns an `asn` data structure that has a `name` key so `asn.name` is the equivalent of `org`.

**Comment by arielkr256** [comment]
We may revisit this once we have more than one supported geolocation enrichment provider.
