### ISSUE TITLE
Improve instructions for contributions

### ISSUE THREAD

**Issue by kbroughton** [panther-labs/panther-analysis#441]
The contributing doc is here.

https://github.com/panther-labs/panther-analysis/blob/master/CONTRIBUTING.md

Rather than the existing GitHub actions which are panther-labs specific and have to be manually disabled in a forked org, it would be nice to have all the linting run as a GitHub action so that PRs could be submitted with no extra surprises.
Panther-analysis uses a mix of Circleci and GitHub actions. It might make more sense to migrate the python linting (via bandit) to a github action so that other teams get the benefit of automating this step.

```
#!/bin/bash -eo pipefail
make lint
pipenv run bandit -r aws_account_policies aws_acm_policies aws_cloudformation_policies aws_cloudtrail_policies aws_cloudtrail_rules aws_cloudwatch_policies aws_config_policies aws_dynamodb_policies aws_ec2_policies aws_elb_policies aws_guardduty_policies aws_guardduty_rules aws_iam_policies aws_kms_policies aws_load_balancer_policies aws_rds_policies aws_redshift_policies aws_s3_policies aws_s3_rules aws_vpc_flow_rules aws_vpc_policies aws_waf_policies box_rules cisco_umbrella_dns_rules crowdstrike_rules data_models gcp_audit_rules github_rules global_helpers gravitational_teleport_rules gsuite_activityevent_rules gsuite_reports_rules indicator_creation_rules okta_rules onelogin_rules onepassword_rules osquery_rules panther_audit_rules panther_ioc_rules standard_rules templates zendesk_rules zoom_operation_rules --skip B101  # allow assert statements in tests
```

In addition, I believe there is something that automatically converts single quotes to double quotes in the .py and/or .yml files.
I don't recall this showing up when I made the PR, but when I tried to pull in upstream, I got merge conflicts.

**Comment by edyesed** [comment]
@kbroughton we added some controls on the github actions to restrict them to running only on the panther-labs organization owned codebase.
