### ISSUE TITLE
check_account_age key incorrect for AWS accounts

### ISSUE THREAD

**Issue by nathan-williams-lightspeed** [panther-labs/panther-analysis#494]
The check for AWS account age uses the account ID as the key:
https://github.com/panther-labs/panther-analysis/blob/e45530f8261cf404e3bbdfb7e770ba3f608a19cf/rules/aws_cloudtrail_rules/aws_console_login_without_mfa.py#L55

However when a new account is created, the key is `"new_account - " + account_id`:
https://github.com/panther-labs/panther-analysis/blob/e45530f8261cf404e3bbdfb7e770ba3f608a19cf/rules/indicator_creation_rules/new_aws_account_logging.py#L33

**Comment by arielkr256** [comment]
Fixed by https://github.com/panther-labs/panther-analysis/pull/1237
