### ISSUE TITLE
Investigate How the dynamo client is created in globals

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther-analysis#50]
As @austinbyers points out, we can probably construct the dynamo client used in the default `global` in a better way:

https://github.com/panther-labs/panther-analysis/pull/49#discussion_r413397967

We need to look into why we did it this way, and if we can do something better.

**Comment by nhakmiller** [comment]
Austin changed this already.

**Comment by austinbyers** [comment]
Haha I had no idea I implemented my own feedback almost exactly how I laid it out more than a month ago :P

Fixed in #54
