### ISSUE TITLE
remove_from_string_set fails if removing all items

### ISSUE THREAD

**Issue by nathan-williams-lightspeed** [panther-labs/panther-analysis#524]
If `remove_from_string_set` is passed the full set (so the final result would be an empty set in DynamoDB), the response from boto3 does not contain an `Attributes` key, causing an exception here:

https://github.com/panther-labs/panther-analysis/blob/fdf1ed2cbda9d03a78c7925d5c976dc0cc5c0f29/global_helpers/panther_oss_helpers.py#L320

**Comment by arielkr256** [comment]
https://github.com/panther-labs/panther-analysis/blob/release/global_helpers/panther_oss_helpers.py#L228
